#baseURL = 'https://example.org/'
#languageCode = 'en-us'
#title = 'My New Hugo Site'

baseURL = 'http://localhost:5000'
languageCode = 'en-us'
title = 'aruka /b/'
theme = 'GitHub Style'

[params]
  avatar = 'alicia.png'
  github = 'Sakaki-Aruka'
  location = 'Japan'
  favicon = 'alicia.png'
  author = 'Sakaki Aruka'
